import React, { useState } from 'react';
import { Button } from '../ui/button';

type Props = {
  onNavigateLogin: () => void;
  onNavigateSignup: () => void;
};

export function HomePage({ onNavigateLogin, onNavigateSignup }: Props) {
  const [smile, setSmile] = useState(false);

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-green-50 via-white to-blue-50 p-8">
      <div className="max-w-5xl w-full grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
        {/* Left: Marketing text */}
        <div className="space-y-6 px-6">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-gray-900">AI Student Assistant</h1>
          <p className="text-lg text-gray-600">Your friendly AI companion for studying — summarize notes, generate flashcards, practice quizzes and get instant help with coursework.</p>

          <div className="flex items-center gap-4">
            <Button
              className="px-6 py-3 text-base bg-green-600 hover:bg-green-700 transform hover:-translate-y-1 transition-all"
              onMouseEnter={() => setSmile(true)}
              onMouseLeave={() => setSmile(false)}
              onClick={onNavigateSignup}
            >
              Sign up
            </Button>

            <Button
              variant="outline"
              className="px-6 py-3 text-base hover:-translate-y-1 transition-all"
              onMouseEnter={() => setSmile(true)}
              onMouseLeave={() => setSmile(false)}
              onClick={onNavigateLogin}
            >
              Log in
            </Button>
          </div>

          <div className="mt-6 text-sm text-gray-500">
            <strong>Tip:</strong> Try uploading a PDF in Notes to see instant summaries and flashcards generated by the AI (demo-ready on this project).
          </div>
        </div>

        {/* Right: Cute student illustration */}
        <div className="flex items-center justify-center">
          <div className="relative w-80 h-80 bg-white rounded-3xl shadow-2xl flex items-center justify-center overflow-hidden">
            {/* Floating books */}
            <div className="absolute -left-8 -top-6 animate-float-slow opacity-80">
              <div className="w-20 h-12 bg-yellow-200 rounded-md rotate-6 shadow-inner" />
            </div>
            <div className="absolute -right-8 -bottom-6 animate-float-fast opacity-80">
              <div className="w-24 h-14 bg-pink-200 rounded-md -rotate-6 shadow-inner" />
            </div>

            {/* SVG Student */}
            <div className="z-10 p-6">
              <svg width="220" height="220" viewBox="0 0 220 220" xmlns="http://www.w3.org/2000/svg">
                <defs>
                  <linearGradient id="hairGrad" x1="0%" x2="100%">
                    <stop offset="0%" stopColor="#6B46C1" />
                    <stop offset="100%" stopColor="#805AD5" />
                  </linearGradient>
                </defs>
                <g transform="translate(110,110)">
                  {/* body */}
                  <ellipse cx="0" cy="60" rx="52" ry="36" fill="#F6E05E" opacity="0.9" />
                  {/* head */}
                  <circle cx="0" cy="-18" r="44" fill="#FFDAB9" stroke="#FBD38D" strokeWidth="2" />
                  {/* hair */}
                  <path d="M-32 -30 C -30 -60, 30 -60, 32 -30" fill="url(#hairGrad)" />
                  {/* eyes */}
                  <g fill="#111827">
                    <circle cx="-14" cy="-20" r="4" />
                    <circle cx="14" cy="-20" r="4" />
                  </g>
                  {/* rosy cheeks */}
                  <g fill="#FBCFE8" opacity="0.9">
                    <ellipse cx="-26" cy="-10" rx="7" ry="5" />
                    <ellipse cx="26" cy="-10" rx="7" ry="5" />
                  </g>
                  {/* mouth - switches on smile state */}
                  {smile ? (
                    <path d="M -18 0 Q 0 18 18 0" stroke="#374151" strokeWidth="3" fill="none" strokeLinecap="round" />
                  ) : (
                    <path d="M -10 4 Q 0 8 10 4" stroke="#374151" strokeWidth="2" fill="none" strokeLinecap="round" />
                  )}

                  {/* book */}
                  <g transform="translate(-30,30)">
                    <rect x="-8" y="-6" width="40" height="28" rx="3" fill="#60A5FA" />
                    <rect x="-6" y="-4" width="36" height="24" rx="2" fill="#BFDBFE" />
                    <rect x="-6" y="-4" width="36" height="4" fill="#93C5FD" />
                  </g>
                </g>
              </svg>
            </div>

            {/* Cute sparkles */}
            <div className="absolute top-6 right-6 opacity-80 animate-pulse text-yellow-400">✨</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default HomePage;
